Create books collection.
Lanr3waju/Awesome-Books-Project pull request #3
Opened 2022-03-09 15:48 UTC by Lanr3waju

# Books Collections with Functions to Add and Remove Books
## This is a `js` project that stores books using `arrays` and `objects`, and implements a number of various `js methods` to make the `add books` & `remove books` function functional.

### This PR does the following;

- Removes non-dynamic elements from the `js` file.
- Implement DOM manipulation in various parts of the project to load the books dynamically
- JS `Objects`, `Arrays`, & `Object Arrays` to store books.
- Implement the use of Arrow Functions `=>` and `{destructure}` methods to match the modern conventions.
- Made use of various `JS` objects and methods such as; `node.createElement()`, `node.AppendChild()`, `node.replaceChild()`, etc. to avoid the use of `innerHTML` for security considerations.
- Implemented `array.forEach()`, through the course of the project to iterate through `objects` in the `Objects Array`; thus making it possible to manipulate the objects and produce the desired result.
- Made use of `if Statements` to match specific use cases.
- Implement the use of `eventListeners` to make 'add' & 'remove' buttons functional.
- Implement the use of `array. find()` & `parseInt` to locate the specific books to remove when the appropriate button is clicked.
- The `JSON` API `stringify` & `parse` were implemented, to enable JS Objects to be used on windows local storage.
- The `node.localStorage` `set()` & `get()` methods were used to store and retrieve updated books.

#### A live demo link is provided [here](https://lanrewaju-elib.netlify.app/) for accessing the live app.

2022-03-12 22:08 UTC, adejam requested changes
## Looks good overall. Let's fix the issues mentioned in the review

Also Let's make our code more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and [Solid](https://www.digitalocean.com/community/conceptual_articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design)

2022-03-12 22:08 UTC, adejam commented on js/index.js
> +const addBookButton = document.querySelector('.add-book');
It's best to use `id` when targetting one element alone. This gives more clarity to the code.

2022-03-12 22:08 UTC, adejam commented on js/index.js
> +  });
Nothing seems to happen when the add book feature gets called. I guess the functionality to add a new book is being triggered elsewhere, this looks hacky and can be improved on

2022-03-13 15:00 UTC, Lanr3waju commented on js/index.js
> +const addBookButton = document.querySelector('.add-book');
refactored, thanks

2022-03-14 09:18 UTC, merged